import Head from 'next/head'

interface CustomHeadProps {
  title: string
}

const CustomHead = ({ title }: CustomHeadProps): JSX.Element => {
  return (
    <Head>
      <title>{title}</title>
      <meta
        name="description"
        content="Generated by create next app"
        data-testid="description-tag"
      />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
        data-testid="viewport-tag"
      />
      <link rel="icon" href="/favicon.ico" data-testid="favicon-tag" />
    </Head>
  )
}

export default CustomHead
